package ast.E;

public enum TipoE {
  OR, AND,
  IGUALIGUAL, MAYOR, MENOR, MAYORIGUAL, MENORIGUAL, DISTINTO,
  SUMA, RESTA, MUL, DIV, MOD,
  ELEV, NOT,
  ENT, VERDADERO, FALSO, IDEN, FUNCION,
}
