
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Tue Apr 13 17:10:32 CEST 2021
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int DISTINTO = 9;
  public static final int POT = 16;
  public static final int CONST = 43;
  public static final int TIPO = 22;
  public static final int POR = 13;
  public static final int CASE = 41;
  public static final int INT = 34;
  public static final int PUNTOCOMA = 33;
  public static final int LLAVE_C = 28;
  public static final int LLAVE_A = 27;
  public static final int NOT = 17;
  public static final int MENORIGUAL = 8;
  public static final int AND = 3;
  public static final int IGUAL = 10;
  public static final int OR = 2;
  public static final int DIV = 14;
  public static final int IF = 36;
  public static final int MAYORIGUAL = 7;
  public static final int BOOLEAN = 35;
  public static final int EOF = 0;
  public static final int RETURN = 38;
  public static final int TRUE = 29;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int COMA = 32;
  public static final int MENOS = 12;
  public static final int MENOR = 6;
  public static final int MOD = 15;
  public static final int VOID = 45;
  public static final int PUNTERO = 20;
  public static final int SWITCH = 40;
  public static final int MAYOR = 5;
  public static final int ENT = 23;
  public static final int ELSE = 37;
  public static final int PUNTO = 31;
  public static final int IDEN = 24;
  public static final int IGUALIGUAL = 4;
  public static final int WHILE = 39;
  public static final int DEFAULT = 42;
  public static final int PAREN_C = 26;
  public static final int PAREN_A = 25;
  public static final int COR_C = 19;
  public static final int FALSE = 30;
  public static final int COR_A = 18;
  public static final int STRUCT = 44;
  public static final int MAS = 11;
}

