
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Apr 03 22:44:49 CEST 2021
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int POT = 26;
  public static final int CONST = 34;
  public static final int POR = 8;
  public static final int GE = 17;
  public static final int CASE = 40;
  public static final int INT = 28;
  public static final int LLAVE_C = 19;
  public static final int LLAVE_A = 18;
  public static final int NOT = 13;
  public static final int AND = 11;
  public static final int IGUAL = 2;
  public static final int LT = 14;
  public static final int OR = 12;
  public static final int DIV = 9;
  public static final int IF = 24;
  public static final int LE = 16;
  public static final int BOOLEAN = 38;
  public static final int EOF = 0;
  public static final int RETURN = 37;
  public static final int TRUE = 30;
  public static final int NEW = 42;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int MENOS = 7;
  public static final int MOD = 10;
  public static final int VOID = 33;
  public static final int PUNTERO = 43;
  public static final int SWITCH = 36;
  public static final int PCOMA = 4;
  public static final int ENT = 45;
  public static final int ELSE = 32;
  public static final int PUNTO = 5;
  public static final int IDEN = 44;
  public static final int IGUALIGUAL = 27;
  public static final int WHILE = 35;
  public static final int DEFAULT = 39;
  public static final int THEN = 29;
  public static final int PAREN_C = 23;
  public static final int PAREN_A = 22;
  public static final int COR_C = 21;
  public static final int FALSE = 31;
  public static final int COR_A = 20;
  public static final int STRUCT = 41;
  public static final int GT = 15;
  public static final int DO = 25;
  public static final int MAS = 6;
}

