
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Mon Apr 12 14:13:05 CEST 2021
//----------------------------------------------------

package constructorast;

/** CUP generated class containing symbol constants. */
public class ClaseLexica {
  /* terminals */
  public static final int MOD = 14;
  public static final int MENOS = 11;
  public static final int AND = 3;
  public static final int IGUALIGUAL = 4;
  public static final int MENOR = 6;
  public static final int OR = 2;
  public static final int MENORIGUAL = 8;
  public static final int NOT = 16;
  public static final int IDEN = 23;
  public static final int TRUE = 26;
  public static final int POT = 15;
  public static final int COR_C = 18;
  public static final int POR = 12;
  public static final int COR_A = 17;
  public static final int TIPO = 21;
  public static final int COMA = 28;
  public static final int PAREN_C = 25;
  public static final int DISTINTO = 9;
  public static final int MAYOR = 5;
  public static final int EOF = 0;
  public static final int PAREN_A = 24;
  public static final int DIV = 13;
  public static final int PUNTERO = 19;
  public static final int MAYORIGUAL = 7;
  public static final int FALSE = 27;
  public static final int error = 1;
  public static final int NEW = 20;
  public static final int ENT = 22;
  public static final int MAS = 10;
}

